### ISSUE TITLE
.quote author parsing means that ambiguous errors are produced

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#106]
Today, the following command was run:
> .quote add "They're launching a Death Star at us and you're still talking about the soda!? - @\Fighter Ofthemoonman

to which the bot should probably be like "missing quote mark", but instead it said "Couldn't find any quotes with that author!"

This is because it parsed the message as asking for quotes with the author literally being
> add "They're launching a Death Star at us and you're still talking about the soda!? - @\Fighter Ofthemoonman

which obviously produced no results.

It might be looking for `.quote authorname` before `.quote add` (a subcommand), which isn't very helpful here. (I doubt it though, for reasons given in the next paragraph.) This may want to be reordered, or have the `.quote authorname` parser be more strict (limited to one word, a mention or quoted?) so that errors like this do not trip it up.

Interesting to note however: commands with no arguments are correctly parsed as the subcommand, e.g. `.quote random` correctly pulls up a random quote rather than querying with the author name "random". As such, I think they are already reordered, but what is happening is that it fails to do a `.quote add` and then tries to do `.quote authorname` (succeeding to parse, but then erroring). This needs more investigation.

**Comment by L0neGamer** [comment]
One potential "fix" to this is to remove the `.quote authorname` functionality. Since nicknames and authors of quotes are completely free form, there are a lot of potential issues with allowing the `authorname` base command calling.

If we want to keep this functionality, then I have two suggestions, one of which is more invasive than the other: 
 - when parsing for the `authorname`, look either for a single "word" (mentions and such are acceptable), or a quoted string. This may help, although it will still likely give strange errors messages (likely to do with the fact the `authorname` isn't in a format it expects).
 - somehow make subcommand parsing errors fail out of the command altogether. This means that the `quote add` subcommand parser would fail, then the entire command would fail with an appropriate message from the subcommand. This may need a rework of the subcommand parsing structure, which could be an issue potentially?
